"""Add order tracking fields to User model

Revision ID: 6bfda1b83bb8
Revises: 278b2d200681
Create Date: 2024-10-02 13:32:22.661209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfda1b83bb8'
down_revision = '278b2d200681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column('total_orders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_order_date',
                            sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column('total_spent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_spent')
        batch_op.drop_column('last_order_date')
        batch_op.drop_column('total_orders')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
